### PR TITLE
Add the Max Character Limit linter

### PR DESCRIPTION
**Pull request by kenliao94**
Somehow linter.js is not running my new linter after merging in change #216. However, this linter could work if it could run. I am looking into why it doesn't run.

### CODE REVIEW

**Comment by kenliao94** [comment]
Not ready for review

**Comment by shellscape** [comment]
The first step would be to create specs for this linter. I would start debugging there, first.

**Comment by jwilsson** [comment]
Hi,
Looks good so far! Just two things for now:

1. You'll need to add the linter to the array at the top of `linter.js` for it to be called.
2. I think you'll need to merge in the latest `master` so we don't lose any changes.

**Comment by kenliao94** [comment]
Set the limit to 100 and put that in the default linter array in linter.js. Thanks for the help @jwilsson :)

**Comment by kenliao94** [comment]
Is there a way to locally run those build checks?

**Comment by jwilsson** [comment]
@kenliao94 I think you'll need to run `git fetch` first and then merge.

You can run `npm test` locally to make sure everything passes :)

**Comment by kenliao94** [comment]
Thanks @jwilsson :) But I have ran `git fetch upstream/master` then `git merge upstream/master` it said my local master is already up-to-date with the upstream/master. I ran `git log` and the history shows I have merged in the latest commit on master:

commit 92d1e3610a40ff8de800b8c120833ab510edb5f0                                                                                                              
Author: Jonathan Wilsson <jonathan.wilsson@gmail.com>                                                                                                           
Date:   Sun Jul 31 16:54:24 2016 +0200                                                                                                              
2.0.2  

Is there any changes you want me to merge in this pull request?

**Comment by kenliao94** [comment]
Sorry @jwilsson , this is my first time making a PR to an open source project. Do you want me to merge in other people's changes? Thanks for your patience.

**Comment by jwilsson** [comment]
@kenliao94 No worries, I'm happy to help :)

This sounds really strange, the thing I'm hung up about is the removal of
```
"allowNewline": false, 
```

in `lib/config/defaults.json` which shouldn't be shown as deleted with latest master but we can take care of that when it's time to merge.

**Comment by shellscape** [comment]
Maybe a rebase will fix it?

**Comment by kenliao94** [comment]
Hi @shellscape , I tried 
`git rebase upstream/master`
Still didn't see the changes @jwilsson mentioned. That's weird. Here's what I got after running 
`git remote -v` 

`
origin  https://github.com/kenliao94/lesshint (fetch)                                                                                                                      
origin  https://github.com/kenliao94/lesshint (push)
upstream        https://github.com/lesshint/lesshint (fetch)
upstream        https://github.com/lesshint/lesshint (push) 
`

Also, it is failing the coverage test, do I add testcases to increase that coverage?

Thanks!

**Comment by jwilsson** [comment]
@kenliao94 I'm still hoping that it'll sort itself out. 

Some tests will be needed, yes. That should solve the decrease in coverage automatically.

**Comment by kenliao94** [comment]
Still need to look into why my linter under these testcases always return empty array but ran correctly from terminal.

**Comment by kenliao94** [comment]
Also need to add a testcase for multiple lines exceeding character limit.

**Comment by kenliao94** [comment]
Fixed test issue & added one more testcase. If all checks pass, ready for review and merge

**Comment by kenliao94** [comment]
@shellscape  & @jwilsson Thanks for all your help!

**Comment by jwilsson** [comment]
Awesome, I'm good! 🎉 

And thanks for fixing the `spaceAroundComma` setting!

Let's see if anyone else has any comments before merging.

**Pull request merged**
