### PR TITLE
propertyUnits: valid, invalid specification. addresses #36

### PR DESCRIPTION
**Pull request by shellscape**
propertyUnits: valid, invalid specification. addresses #36

### CODE REVIEW

**Comment by kokarn** [comment]
This looks good and because you are so quick with the PRs i'd like to merge.
Mind having a look on the failing tests?

**Comment by shellscape** [comment]
@kokarn no idea what's up with that. they were passing locally.

**Comment by shellscape** [comment]
updating to gonzales-pe @ 3.0.0-beta was the cause of some of the errors. I reverted the commit.

**Comment by kokarn** [comment]
Can you update the PR?

**Comment by shellscape** [comment]
@kokarn in what way? specs are passing locally. I don't know why either services are failing.

**Comment by kokarn** [comment]
Hmm, I guess we need to specify the correct version of gonzales-pe. Wouldn't the tests failing on Travis and Appveyor mean that it's using the wrong version?

**Comment by shellscape** [comment]
I reverted the commit that was using 3.0.0-beta, and it's back to 3.0.0-31, which is what master is using.

**Comment by kokarn** [comment]
Hmm, this is weird. There is only the one commit for this PR so it shouldn't fail :/

**Comment by shellscape** [comment]
For whatever reason, I had to blow away and reclone to start seeing the failing specs. Anyhow, it's due to the propertyUnits change. There's one more error being thrown on the checkDirectory specs:

```
{ column: 19,
      line: 2,
      linter: 'propertyUnits',
      message: 'Unit "px" is not allowed for "margin-bottom".',
      file: 'vendor.less',
      source: '    margin-bottom:10px;',
      severity: 'warning' }
```

I ran into this yesterday with our internal linting. Because propertyUnits is on by default, and by default there are no units specified, **all** units are invalid.

I'm thinking this is a candidate for a disabled-by-default linter. Thoughts?

**Comment by kokarn** [comment]
I'd say the defaults are messed up, not that it should be disabled.

A little googling gave me [this list](http://www.w3.org/TR/css3-values/)
`em`, `ex`, `ch`, `rem`
`vw`, `vh`, `vmin`, `vmax`
`cm`, `mm`, `q`, `in`, `pt`, `pc`, `px`
`deg`, `grad`, `rad`, `turn`
`s`, `ms`
`Hz`, `kHz`
`dpi`, `dpcm`, `dppx`

My suggestion is to enable `deg`, `rad`, `s`, `dpi`, `dppx`, `em`, `rem`, `vw`, `vh` and `px` and disable the rest.

**Comment by shellscape** [comment]
Do any of our other linters follow that pattern? (Of having a linter option populated with defaults)

**Comment by shellscape** [comment]
Ah ignore that. Just found this in defaults.json:

```
    "propertyUnits": {
        "enabled": true,
        "global": [
            "ch", "em", "ex", "rem",                 // Font-relative lengths
            "cm", "in", "mm", "pc", "pt", "px", "q", // Absolute lengths
            "vh", "vw", "vmin", "vmax",              // Viewport-percentage lengths
            "deg", "grad", "rad", "turn",            // Angle
            "ms", "s",                               // Duration
            "Hz", "kHz",                             // Frequency
            "dpi", "dpcm", "dppx",                   // Resolution
            "%"                                      // Other
        ],
        "properties": {}
    },
```

So I missed the defaults config file. Fixing that...

**Comment by kokarn** [comment]
Looks like a missed `%` as well :)

**Comment by kokarn** [comment]
Jay! Great work @shellscape.

**Pull request merged**
