### PR TITLE
Add support for inline disabling/enabling of rules

### PR DESCRIPTION
**Pull request by jwilsson**
Here it is, the big one. The million dollar feature. Inline configuration!

This PR gives us the possibility to do these kind of things:
```less
// lesshint spaceBeforeBrace: false, emptyRule: false
.foo{ // Won't be reported
    color: red;
}

.bar {

} // Won't report this empty rule

// lesshint emptyRule: true
.baz{

} // But this will be reported, but the missing space before { won't

.foobar { // The next line won't be reported
    color:blue; // lesshint-line spaceAfterPropertyColon: false
}
```

As shown, all rules that aren't scoped to a single line are disabled until they're reenabled. At this time, rules that are disabled in `.lesshintrc` will stay disabled and I think that makes most sense.

I tried to make it as liberal as possible with regards to spaces. The only space that's required is the one after `lesshint` and `lesshint-line` (to prevent collisions) but other than that you're free to put spaces (or not) wherever you want, before `lesshint`, before `:` and so on.

I left the names open to give us the ability to add more configuration options to each rule in the future, for example changing `style` options inline (anything that's valid JSON is what I'm thinking really). This is the same way as ESLint does it.

But if anyone's got any better name suggestions, please share them!

Ref: #55

### CODE REVIEW

**Comment by kokarn** [comment]
Looks good, great job dude! 
Only thing i have questions about is this
> At this time, rules that are disabled in .lesshintrc will stay disabled and I think that makes most sense.

What does that mean exactly?

**Comment by jwilsson** [comment]
@kokarn It means that a rule that's disabled in `.lesshintrc` can't be enabled inline, for example:

.lesshintrc:
```
{
    ...
    stringQuotes: false
}
```

file.less:
```
// lesshint stringQuotes: true
.foo {
    background: url("image.png"); // Still won't report this
}
```

**Comment by shellscape** [comment]
Ooo I have to disagree with that choice. That's counter-intuitive, and removes quite a bit of flexibility. There may be specific files that you want to enforce rules which have otherwise been disabled. That may be an edge case, but this happens to be a utility which caters to the edge cases, and the inline rulesets are specifically for even more granularity.

**Comment by kokarn** [comment]
+1 for @shellscape 
Why would you not want to be able to enable a specific rule in one place only?

**Comment by adam-lynch** [comment]
:+1: 

To confirm, if I want to disable something for two lines, I'd do this?

```less
.a {
    color: red;
    // lesshint aRule: false
    background: blue;
    outline: 1px solid green;
    // lesshint aRule: true
}

```

**Comment by shellscape** [comment]
the more I look at that setup, the more it rubs on me. I'm a big big fan of the way that jshint/eslint does it. the inline config should really only affect the line after it. jshint allows you to disable the linters altogether for a range, but I'm not a fan of turning off a rule for one line and having to turn it back on on the line after. that creates a lot of unneeded cruft for what I imagine will be sparing use. 

sorry, not trying to be difficult on this one, but definitely have preferences.

**Comment by jwilsson** [comment]
@adam-lynch Yes, exactly.

@shellscape, @kokarn You have a point in wanting to enable rules inline but I think it's a bit tricky right now (getting default options, , etc.). Perhaps we can leave it like this for now and keep iterating on it in later versions?

But I'm not sure I follow you, @shellscape, perhaps I gave a bad example in my initial comment. You can disable a single line by adding the comment at the end of it and that will only affect that line. If I'm reading the ESLint and JSHint docs correctly, that's how they do it too, albeit with a slightly different comment syntax but the usage is the same. Not trying anything here, just wanna make sure we understand each other :)

**Comment by kokarn** [comment]
Ah, hmm. Should we really merge things just to improve on them later?

What I think shellscape is saying is that ESLint doesn't allow enabling for a whole block, only single lines. Correct?

**Comment by shellscape** [comment]
This should clear up what I was trying to convey, and is what I'd recommend we follow: http://jshint.com/docs/#inline-configuration. It's highly effective. 

I'm in favor of iteration in 99% of situations. Since the feature is particularly limited by not being able to turn on linters inline, that will constitute a potentially breaking change and following semver will be a minor version. As long as that won't hold up completing the feature in the future, I'm good with it.

**Comment by kokarn** [comment]
Suggestion: 
Only line-scopes, nothing for a block.
Maybe an exception for the whole file, but don't really like that. 
Might be needed for some specific files tho.

**Comment by jwilsson** [comment]
@kokarn's suggestion is what we decided upon in #55 and I got carried away when starting to implement it. My bad!

I've added some of it, and just gonna finish up the last part of single line options before we're done. When I'm done, it'll be what we decided upon in #55 with the possibility to enable rules that are disabled in `.lesshintrc` as well.

**Comment by kokarn** [comment]
Jay! Sounds like a great plan.

**Comment by jwilsson** [comment]
After a lot of work and thinking I don't think it's possible to enable rules for a single line at this moment because of the way we're passing nodes to each linter. And quite frankly, I don't see the need for it either. I do, however, see the need to enable a disabled rule (or set other options for it) at the top of a file (which will be possible) but the single line option will only be able to disable it.

No other linter (JSHint, ESLint) allows it either. JSHint just uses a rule given earlier or falls back to defaults/a config file. And ESLint analyzes the whole file so a rule option given inline is applied everywhere (even if it occurs further down in the file).

But, to summarize:
* A comment at the top of a file will allow you to enable, disable, and configure linter(s) using the same format as in `.lesshintrc` (even a bit relaxed, not as strict as actual JSON).
* A trailing comment on a line will allow you to disable the specified linter(s) for that line.

Does this sound OK for everyone?

**Comment by kokarn** [comment]
Yeah, sounds like a good way forward

**Comment by miloszsobczak** [comment]
Actually this feature is something I was expecting when I first heard of this package, so for me - sounds great ;)

**Comment by jwilsson** [comment]
If no one's got any objections I'll merge this tonight (CET) and tag a `1.4.0`.

**Comment by jwilsson** [comment]
Merged in cf757cd9741cffeef966885de76168d50dc58716.

**Pull request closed without merging**
