### PR TITLE
initial commit of linter refactor concept, for discussion only

### PR DESCRIPTION
**Pull request by shellscape**
This pull request is intended to be for discussion only. If consensus is reached, changes will be implemented clean on a new branch. Referencing: #56 

NOTE: specs have not been updated to accommodate these changes.

### CODE REVIEW

**Comment by jwilsson** [comment]
I think it looks great! Awesome work!

I definitely think we should continue iterating on this. @kokarn what do you think?

**Comment by kokarn** [comment]
Oh, forgot to check this out. Yeah, looks good as always.

**Comment by shellscape** [comment]
Been a bit of a nutty week. I'm off the grid until Monday, but I'll make an effort to get this wrapped up on Tuesday when I return.

**Comment by shellscape** [comment]
Since discussion has concluded, working on the actual branch for the refactor.

**Pull request closed without merging**
