### PR TITLE
Update gulp-mocha to 3.x

### PR DESCRIPTION
**Pull request by jwilsson**
The title says it all. Nothing more, nothing less.

### CODE REVIEW

**Comment by KennyLindahl** [comment]
A recommendation is to always specify specific versions to ensure that it's always stable.
Eventually the libs will be incompatible or change API.

Maybe we want to do this change in this PR as well?

Also it looks like the AppVeyor build failed, or is this expected in certain Node versions?
Would be good to get rid of it in any case.

**Comment by shellscape** [comment]
@KennyLindahl have to disagree with the use of caret - that's the preferred modifier to use these days. https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004 "Allows changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple. ... Caret ranges are ideal when an author may make breaking changes between 0.2.4 and 0.3.0 releases"

**Comment by KennyLindahl** [comment]
@shellscape It's a recommendation, so it can be ignored if you don't agree. However i speak from my own experience, i've seen it break multiple times because of this.

**Comment by shellscape** [comment]
if someone is ignoring semver, then yes it can break. that's pretty edge-casey to go worrying about when it's so widely used, the default that NPM uses out of the box, and the likelihood that someone at mocha will ignore semver best practices (they'd be lambasted by the community).

**Comment by KennyLindahl** [comment]
Yes, it is edge case, but it is safer. But go ahead and ignore if you don't agree.

**Comment by jwilsson** [comment]
@KennyLindahl Thanks for the input. I don't know why AppVeyor failed (it just hung and didn't even try to install anything), a restart and everything is fine.

But I think it's OK to run with `^` which we do for everything else too. If something were to break (which I highly doubt) we'll deal with it then. But again, thanks for the input, highly appreciated!

I'll merge this then since there doesn't seem to be any other comments.

**Pull request merged**
