### PR TITLE
adding spec for #222 assertion

### PR DESCRIPTION
**Pull request by shellscape**

### CODE REVIEW

**Comment by shellscape** [comment]
@jwilsson appveyor is such a punk. why's it always failing?

**Comment by jwilsson** [comment]
@shellscape I don't know, I'll restart it and see if that helps. Not really satisfied with it but haven't found a replacement :/

**Comment by shellscape** [comment]
@jwilsson it doesn't seem to be picking up the new version of postcss-values-parser

**Comment by jwilsson** [comment]
It seems it won't invalidate the `node_modules` cache, I'll try to invalidate it with something like this: https://www.appveyor.com/docs/build-cache#cache-dependencies

**Comment by jwilsson** [comment]
That did the trick 🎉 

Merging!

**Pull request merged**
