### PR TITLE
Property Ordering by Alpha

### PR DESCRIPTION
**Pull request by srogers202**
Thanks for all the hard work guys!

I just ran into the question of ordering properties alphabetically. I noticed that the issue was brought up, so I put something together really quick. Let me know how it looks.

@jsdevel

### CODE REVIEW

**Comment by jsdevel** [comment]
+1

**Comment by jwilsson** [comment]
Great job! Just some minor things as per the notes, then we're good to go.

**Comment by srogers202** [comment]
@jwilsson Thanks for the feedback.

**Comment by kokarn** [comment]
Really nice! Like it a lot :thumbsup:

**Comment by shellscape** [comment]
Thanks for this one @srogers202 !

**Pull request merged**
