### PR TITLE
Account for trailing whitespace in newlineAfterBlock

### LINKED ISSUE #245: newlineAfterBlock with nested blocks
Hello,

if got problems to resolve the following warning(s)

```
Warning: app.less: line 1636, col 5, newlineAfterBlock: All blocks should be followed by a new line.
Warning: app.less: line 1641, col 3, newlineAfterBlock: All blocks should be followed by a new line.
Warning: app.less: line 1644, col 5, newlineAfterBlock: All blocks should be followed by a new line.
Warning: app.less: line 1649, col 3, newlineAfterBlock: All blocks should be followed by a new line.
Warning: app.less: line 1652, col 5, newlineAfterBlock: All blocks should be followed by a new line.
Warning: app.less: line 1657, col 3, newlineAfterBlock: All blocks should be followed by a new line.
Warning: app.less: line 1660, col 5, newlineAfterBlock: All blocks should be followed by a new line.
```
It works not on nested blocks for me. Here is my less source: (starting from line 1631)

```
/* Animations */
[ui-view] {
  &.ng-enter {
    opacity: 0;
    transition: 0.25s linear all;
    &.ng-enter-active {
      opacity: 1;
    }
  }

  &.ng-add {
    opacity: 0;
    transition: 0.25s linear all;
    &.ng-add-active {
      opacity: 1;
    }
  }

  &.ng-leave {
    opacity: 1;
    transition: 0.25s linear all;
    &.ng-leave-active {
      opacity: 0;
    }
  }

  &.ng-remove {
    opacity: 1;
    transition: 0.25s linear all;
    &.ng-remove-active {
      opacity: 0;
    }
  }
}
```

I found nothing about nested formatting in your documentation, so I tried some cases but always got

`newlineAfterBlock: All blocks should be followed by a new line.`

or

`trailingWhitespace: There should't be any trailing whitespace.`

How should the less code structured to remove the warning? Or is it a bug?

### PR DESCRIPTION
**Pull request by jwilsson**
Allow trailing whitespace to be present on the empty line. This will hopefully fix #245.

### CODE REVIEW

**Comment by tkazec** [comment]
Personally, I think the way you're building source strings is fragile and will likely cause further issues in the future, because it's not representative of real world use. Can you use multiline strings that preserve formatting? (Plenty of ways to do so – but my favorite is `[].join('\n')`.)

**Comment by shellscape** [comment]
six of one, half dozen of another regarding string building - religious debate relegated to style guides imho.

👍  from me

**Comment by tkazec** [comment]
Technically the way the string is built does not matter, but at least the result should reflect expectations. The original test case did not catch this issue because the formatting in the code did not match the actual content.

**Comment by jwilsson** [comment]
I don't think any test would have caught this, I wouldn't have thought about a line containing trailing whitespace and accounting for that anyway. But I can agree that building strings like this isn't optimal, but we can solve it with template literals once we drop support for older Node versions.

BTW, PRs for enhancing things are always welcome! 😉

**Pull request merged**
