### PR TITLE
feat(singleLinePerProperty): allow inline comments

### LINKED ISSUE #51: False positive with "singleLinePerProperty"
`singleLineProperty` is returning a false positive for inline comments.

Valid CSS

```LESS
.foo {
  background-color: #000;
  color: #000; // black on black
}
```

Shouldn't error
```
test.less: line 3, col 5, singleLinePerProperty: Each property should be on it's own line.
```

Please add support for inline comments

### PR DESCRIPTION
**Pull request by CITguy**
Closes #51

### CODE REVIEW

**Comment by jwilsson** [comment]
Great job!

Just the small things I mentioned in the commit and we're good to go!

**Comment by CITguy** [comment]
* removed leading underscores
* moved new functions out of `module.export`

**Comment by CITguy** [comment]
Once this is merged, can we get a new version in npm, please?

**Comment by jwilsson** [comment]
Thank you!

A new npm release is coming right up.

**Comment by CITguy** [comment]
Thank you!

**Pull request merged**
