### PR TITLE
Update postcss-less to 0.15

### PR DESCRIPTION
**Pull request by jwilsson**

### CODE REVIEW

**Comment by jwilsson** [comment]
This broke horribly, I'll investigate further tonight.

**Comment by shellscape** [comment]
something to do with the PR for https://github.com/webschik/postcss-less/issues/58?

**Comment by shellscape** [comment]
Yeah, it's directly related to this: https://github.com/webschik/postcss-less/pull/59

I can't figure out why they thought that was a good idea to revert a major prior fix.

**Comment by jwilsson** [comment]
Closing this since it won't ever be merged.

**Comment by shellscape** [comment]
@jwilsson I think we've got another MIA developer over there. I responded to their PR merge and haven't heard anything in nearly a month.

**Comment by jwilsson** [comment]
@shellscape Hmm, if you feel that's the right way to go. Or perhaps just try to help out there? It's up to you!

**Pull request closed without merging**
