### PR TITLE
fix verbiage in url_quotes linter

### PR DESCRIPTION
**Pull request by shellscape**
simple syntax fix

### CODE REVIEW

**Comment by jwilsson** [comment]
Could you squash the commits?

And thanks for fixing my broken English :blush:

**Comment by shellscape** [comment]
Is squashing entirely necessary? There's still a merge commit.

**Comment by jwilsson** [comment]
@shellscape It'll make the history a bit cleaner, just one commit for one change.

**Comment by jwilsson** [comment]
I'm merging this since we're getting ready for a `0.9.1`.

**Comment by shellscape** [comment]
:+1: busy week on my end. I'll keep the commits down moving forward for you

**Pull request merged**
