### PR TITLE
Fix duplicateProperty crashing on local variables

### PR DESCRIPTION
**Pull request by thybzi**
Otherwise crashes on:
```less
.myblock {
    @a: red;
    @b: 3px;
 }
```

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PR. Please add a test for this change.

**Comment by thybzi** [comment]
Is that what you wanted?

**Comment by kokarn** [comment]
Thanks!

**Comment by thybzi** [comment]
Thanks for merging. How soon that change could be brought to https://github.com/lesshint/grunt-lesshint/ ?

**Comment by kokarn** [comment]
It's on it's way, @jwilsson is working on it. 
In the meantime you can install the current master using 
```shell
npm install https://github.com/lesshint/lesshint.git
```
in the grunt-lesshint directory.

**Comment by jwilsson** [comment]
Released in `1.2.2`.

**Pull request merged**
