### PR TITLE
Fixes upstream #124 bug with negative numbers

### PR DESCRIPTION
**Pull request by miloszsobczak**
@jwilsson - I had finally time to fix recent issues with negative numbers. Please take a look,

### CODE REVIEW

**Comment by miloszsobczak** [comment]
made a mistake fix the commit message and it's not replated to issue ;(

**Comment by jwilsson** [comment]
@miloszsobczak Thank you! 

No worries, we might be able to solve it with some creative commit messages :)

**Comment by ErikAGriffin** [comment]
I'm still getting warnings on negative numbers:
`transform: translate(-50%,-50%);`

Warning: file.less: line 192, col 34, spaceAroundOperator: Operators should be preceded and followed by one space.

**Comment by shellscape** [comment]
@ErikAGriffin I believe that 2.0 should resolve that

**Comment by ErikAGriffin** [comment]
Right, I'll check what version is used in my project. Thanks for the prompt reply

**Comment by shellscape** [comment]
@ErikAGriffin 2.0 is coming soon, not yet released

**Pull request merged**
