### PR TITLE
Errors vs warnings

### PR DESCRIPTION
**Pull request by shellscape**
In reference to: https://github.com/lesshint/lesshint/issues/44

This is dependant upon https://github.com/lesshint/lesshint/pull/46

Defines warnings vs errors. Since linters aren't inheriting anything from a parent object and are duplicating a lot of code, the code to allow overriding of their result type will have to be pasted manually in each linter. This PR accounts for missing `type` property on each result and adds the default of `linter.resultType.warning` if it's not found.

This can be considered a minor semver change for the fact that it significantly adds to functionality, or a patch change since it contains no breaking changes.

### CODE REVIEW

**Comment by jwilsson** [comment]
Nice, thanks a lot for working on this!

Let's see if we can refactor the linters into inheriting something from a parent object (or something else to avoid a lot of the duplication.)

However, while I know @kokarn [likes a single object with arrays for each type](https://github.com/lesshint/lesshint/issues/44#issuecomment-133295632) I found the [way ESLint does it](http://eslint.org/docs/developer-guide/nodejs-api.html#linter) really nice. They expose plain objects in an array with a `fatal` property if a parse error is encountered.

With some inspiration from ESLint, our objects could look something like this:
```js
{
    column: 4,
    fatal: false,
    line: 1,
    message: 'Opening curly brace should be preceded by one space.',
    rule: 'spaceBeforeBrace',
    severity: 'warning',
    source: '.foo{'
}
```

What's the majority's opinion on this? If the majority's leaning towards something else we'll obviously go with that.

**Comment by shellscape** [comment]
I don't mind `severity` over `type` at all. It's less ambiguous for sure. Do we need the `fatal` property?

**Comment by jwilsson** [comment]
:+1: Yeah, I thought about the `fatal` property too, I think we can skip it.

Hmm, I guess there's some use for separate arrays in reporters. But I still think it's pretty easy to just filter out all `warning` objects from a large array. `Array.filter()` will handle that, and it will help us keep core a bit lighter.

**Comment by shellscape** [comment]
OK. I'll edit to the new syntax and remove the mapping tomorrow.

**Comment by shellscape** [comment]
I'm back on the task tonight. Should have an update shortly.

**Comment by shellscape** [comment]
Note: This project needs specs around the file property in error results.

**Comment by kokarn** [comment]
@jwilsson Is this ready to merge?

**Comment by jwilsson** [comment]
@kokarn The code looks good, just a test as @shellscape mentioned. 

I'd also like to find a nice way to override the severity on each result. But perhaps we should look at that later? I have some other thoughts on the overall handling of linters too. I'll try to get a issue up for some discussion about all this in the coming days.

**Comment by shellscape** [comment]
I'd say this can be merged then. The test I mentioned would be strictly for redundancy (to make sure no one removed a property) and can be part of another commit. I'll add it to our next sprint if it doesn't get done before then. I'd say it'd be prudent to restructure the linters before providing the overriding mechanism so you/I/we aren't duplicating effort.

**Comment by jwilsson** [comment]
I'll see if I can get a test in during the weekend.

Anyhow, great work and thanks a lot for this @shellscape!

**Comment by jwilsson** [comment]
@kokarn @shellscape Added a test in 35131a87efdfff78bc2ffd001c95abcff9361e7f.

**Comment by shellscape** [comment]
:+1:

**Comment by kokarn** [comment]
Nice

**Pull request merged**
