### PR TITLE
Added a JSON reporter

### LINKED ISSUE #280: Come with a JSON reporter?
Seems like a pretty useful reporter for external tools; is there much problem in adding one by default?

```javascript
/*eslint no-console: 0*/

'use strict';

module.exports = {
    name: 'json',
    report: function report (results) {
        results.forEach(function (result) {
            console.log(JSON.stringify(result));
        });
    }
};
```

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Logs stringified results as JSON.

Fixes #280.

### CODE REVIEW

**Comment by jwilsson** [comment]
Just a small thing I thought of now, do we really want to print a line per object and not just an array with everything?

**Comment by JoshuaKGoldberg** [comment]
Instead of:

```javascript
results.forEach(function (result) {
    console.log(JSON.stringify(result));
});
```

switching to:

```javascript
console.log(JSON.stringify(results));
```

Seems simpler to me. :+1:

**Comment by jwilsson** [comment]
Let's go for it!

**Comment by JoshuaKGoldberg** [comment]
Went for it.

**Pull request merged**
