### PR TITLE
fix(package): update postcss-values-parser to version 1.0.2

### PR DESCRIPTION
**Pull request by jwilsson**
Closes #315

https://greenkeeper.io/

**Which issue, if any, does this resolve?**

**Is there anything in this PR that needs extra explaining or should something specific be focused on?**

### CODE REVIEW

**Comment by shellscape** [comment]
@jwilsson those `TokzenError`s are a result of changes meant to follow the css values spec. Looks like most are to do with operators, for which there are pretty strict validating guidelines. I can loosen that up with an `options` object or some such for Lesshint though.

**Comment by jwilsson** [comment]
@shellscape Yeah, I think some sort of "loose" mode is needed. It's failing on things like `10px+ 10px` which is valid in Less.

**Comment by shellscape** [comment]
cool. so `options.loose` that won't throw the errors and allow parsing through could probably work. I'll try and make that happen today. if you get a sec and want to throw a PR at it, I'll dance a jig and chug a beer.

**Comment by jwilsson** [comment]
Closing this pending completion of https://github.com/lesshint/postcss-values-parser/issues/15.

**Pull request closed without merging**
